#!/bin/bash -e

#©keithhedger Wed 22 May 19:55:26 BST 2013 kdhedger68713@gmail.com

VERSION=$(head ./configure.ac|grep AC_INIT|awk -F [ '{print $3}'|awk -F ] '{print $1}')

svn commit -m ""
cd /tmp
svn co file:///media/LinuxData/Development/SVN/Xfwm4CompositeEditor
find Xfwm4CompositeEditor -name ".svn" -exec rm -rf '{}' \; || true
rm /tmp/Xfwm4CompositeEditor/makepkg
mv /tmp/Xfwm4CompositeEditor /tmp/Xfwm4CompositeEditor-${VERSION}
cd /tmp/Xfwm4CompositeEditor-${VERSION}
./remakesourcelist
aclocal
autoheader
touch NEWS README AUTHORS ChangeLog
automake --add-missing --copy
autoconf
cd ..
tar -czvf Xfwm4CompositeEditor-${VERSION}.tar.gz Xfwm4CompositeEditor-${VERSION}
rm -r /tmp/Xfwm4CompositeEditor-${VERSION}